# Generated by Django 3.1.5 on 2021-02-06 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210206_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutorial',
            name='tutorial_publish',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 6, 22, 5, 32, 570355, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='tutorialseries',
            name='series_summary',
            field=models.CharField(max_length=200),
        ),
    ]
